
#General settings
[general]
	#Set this value to change the thread pool size of asynchronous crock pot recipe matching.
	#Range: 1 ~ 16
	asyncRecipeMatchingPoolSize = 1
	#Set this to false to disable asynchronous crock pot recipe matching.
	asyncRecipeMatching = true
	#Set this to false to disable new players spawning with the Crock Pot Cookbook.
	spawnWithBook = true

