
[Thirst]
	#
	############################################
	#This list defines which items replenish thirst when consumed
	#Items in this list will not give any extra effects
	#-------------------------------------------
	#Default: [farmersdelight:milk_bottle,4]
	#-------------------------------------------
	"Water Containers (Normal)" = ["minecraft:mushroom_stew,1", "crockpot:milk_bottle,4", "create:builders_tea,14"]
	#
	############################################
	#This list defines which items will replenish thirst and energy
	#Items in this list will gived the energized effect when drunk
	#The energized effect will allow the user to operate even if they've not slept for a while and it replenishes energy
	#-------------------------------------------
	#Default: []
	#-------------------------------------------
	"Water Containers (Energizing)" = ["survive:sugar_water_bottle,2"]
	#
	############################################
	#This list defines which items replenish thirst when consumed
	#Items in this list will give the chilled effect when drunk
	#-------------------------------------------
	#Default: [minecraft:potato,0, minecraft:carrot,0, create:builders_tea,8, farmersdelight:tomato_sauce,1, farmersdelight:cabbage,0, farmersdelight:cabbage_leaf,0, farmersdelight:tomato,0, farmersdelight:onion,0, farmersdelight:pumpkin_slice,0, farmersdelight:minced_beef,0, farmersdelight:mixed_salad,0]
	#-------------------------------------------
	"Water Containers (Chilled)" = ["minecraft:beetroot_soup,1", "crockpot:iced_tea,8"]
	#
	############################################
	#Disabling this will disable this mods thirst system
	#-------------------------------------------
	#Default: true
	#-------------------------------------------
	"Boolean: Enable Thirst" = true
	#
	############################################
	#Enabling this will remove the water source block when it is drunk
	#-------------------------------------------
	#Default: false
	#-------------------------------------------
	"Boolean: Remove Source Water Block" = false
	#
	############################################
	#The amount of time in ticks before thirst exaustion is added to the player regardless of what the player is doing. Set to -1 to disable
	#-------------------------------------------
	#Default: 100
	#-------------------------------------------
	#Range: -1 ~ 1000
	"Integer: Idle Thrist Tick Rate" = 100
	#
	############################################
	#Enabling this will remove the water source block when it is drunk
	#-------------------------------------------
	#Default: 0.1125
	#-------------------------------------------
	#Range: 0.0 ~ 4.0
	"Float: Idle Thirst Exhaustion" = 0.1125
	#
	############################################
	#Enabling this allows players to drink water from flowing water sources. This is only allowed for infinite water sources
	#-------------------------------------------
	#Default: false
	#-------------------------------------------
	"Boolean: Drink From Flowing Water" = false
	#
	############################################
	#This list defines which items replenish thirst when consumed
	#Items in this list will give the heated effect when drunk
	#-------------------------------------------
	#Default: [minecraft:rabbit_stew,0, farmersdelight:hot_cocoa,4, farmersdelight:beef_stew,1, farmersdelight:chicken_soup,5, farmersdelight:vegetable_soup,5, farmersdelight:pumpkin_soup,5, farmersdelight:nether_salad,0, farmersdelight:dumplings,0, farmersdelight:stuffed_pumpkin,0, farmersdelight:fish_stew,1, farmersdelight:baked_cod_stew,1, farmersdelight:honey_glazed_ham,-2, farmersdelight:pasta_with_meatballs,0, farmersdelight:pasta_with_mutton_chop,0, farmersdelight:vegetable_noodles,0, farmersdelight:steak_and_potatoes,0, farmersdelight:shepherds_pie,0, farmersdelight:ratatouille,0, farmersdelight:squid_ink_pasta,0, farmersdelight:grilled_salmon,0]
	#-------------------------------------------
	"Water Containers (Heated)" = ["minecraft:rabbit_stew,1", "crockpot:tea,8", "crockpot:hot_cocoa,8"]
	#
	############################################
	#This list defines which items replenish thirst when consumed
	#Items in this list will randomly give the thirst effect when drunk
	#-------------------------------------------
	#Default: [minecraft:spider_eye,-8, minecraft:bread,-6, minecraft:cookie,-1, farmersdelight:raw_pasta,-4, farmersdelight:pie_crust,-2, farmersdelight:slice_of_cake,-2, farmersdelight:slice_of_apple_pie,-2, farmersdelight:slice_of_sweet_berry_cheesecake,-2, farmersdelight:slice_of_chocolate_pie,-2, farmersdelight:sweet_berry_cookie,-1, farmersdelight:honey_cookie,-1, farmersdelight:cooked_rice,-4]
	#-------------------------------------------
	"Water Containers (Thirst)" = ["minecraft:honey_bottle,1"]

[Temperature]
	#
	############################################
	#This determines the mode used when deciding the temperature
	#NORMAL Mode: calculates the average temperature of each block around the player
	#BLEND Mode: calculates the average temperature similar to that of NORMAL, but blends the temperature of the target positions with the player's. The blend ratio is determined by your distance from the block
	#-------------------------------------------
	#Default: BLEND
	#-------------------------------------------
	#Allowed Values: BLEND, NORMAL
	"Enum: Temperature Mode" = "BLEND"
	#
	############################################
	#The speed at which the players temperature will change from their current temperature to the target temperature.
	#Setting it to 1 makes the players temperature change instantly to its target
	#-------------------------------------------
	#Default: 0.001
	#-------------------------------------------
	#Range: 1.0E-4 ~ 1.0
	"Double: Temperature Update Speed" = 0.001
	#
	############################################
	#This list defines the temperatures of blocks
	#Changes to this list will require you to reset your game for them to be applied
	#NOTE: Lava is set to 10.0
	#-------------------------------------------
	#Default: []
	#-------------------------------------------
	"Block Temperatures" = []
	#
	############################################
	#This list defines the temperatures of armors when they're put on
	#Changes to this list will require you to reset your game for them to be applied
	#NOTE: Wool Armor is set to 5.0
	#-------------------------------------------
	#Default: [survive:stiffened_honey_helmet,-5.0, survive:stiffened_honey_chestplate,-5.0, survive:stiffened_honey_leggings,-5.0, survive:stiffened_honey_boots,-5.0, survive:wool_hat,5.0, survive:wool_jacket,5.0, survive:wool_pants,5.0, survive:wool_boots,5.0, minecraft:chainmail_helmet,0.1, minecraft:chainmail_chestplate,0.1, minecraft:chainmail_leggings,0.1, minecraft:chainmail_boots,0.1, minecraft:leather_helmet,4.0, minecraft:leather_chestplate,4.0, minecraft:leather_leggings,4.0, minecraft:leather_boots,4.0, minecraft:iron_helmet,2.7, minecraft:iron_chestplate,2.7, minecraft:iron_leggings,2.7, minecraft:iron_boots,2.7, minecraft:golden_helmet,1.5, minecraft:golden_chestplate,1.5, minecraft:golden_leggings,1.5, minecraft:golden_boots,1.5, minecraft:diamond_helmet,0.5, minecraft:diamond_chestplate,0.5, minecraft:diamond_leggings,0.5, minecraft:diamond_boots,0.5, minecraft:netherite_helmet,1.9, minecraft:netherite_chestplate,1.9, minecraft:netherite_leggings,1.9, minecraft:netherite_boots,1.9, minecraft:turtle_helmet,0.75, ars_nouveau:novice_robes,3.0, ars_nouveau:novice_leggings,3.0, ars_nouveau:novice_hood,3.0, ars_nouveau:novice_boots,3.0, ars_nouveau:apprentice_robes,3.0, ars_nouveau:apprentice_leggings,3.0, ars_nouveau:apprentice_hood,3.0, ars_nouveau:apprentice_boots,3.0, ars_nouveau:archmage_robes,3.0, ars_nouveau:archmage_leggings,3.0, ars_nouveau:archmage_hood,3.0, ars_nouveau:archmage_boots,3.0]
	#-------------------------------------------
	"Armor Temperatures" = ["survive:stiffened_honey_helmet,-5.0", "survive:stiffened_honey_chestplate,-5.0", "survive:stiffened_honey_leggings,-5.0", "survive:stiffened_honey_boots,-5.0", "survive:wool_hat,5.0", "survive:wool_jacket,5.0", "survive:wool_pants,5.0", "survive:wool_boots,5.0", "minecraft:chainmail_helmet,0.1", "minecraft:chainmail_chestplate,0.1", "minecraft:chainmail_leggings,0.1", "minecraft:chainmail_boots,0.1", "minecraft:leather_helmet,4.0", "minecraft:leather_chestplate,4.0", "minecraft:leather_leggings,4.0", "minecraft:leather_boots,4.0", "minecraft:iron_helmet,2.7", "minecraft:iron_chestplate,2.7", "minecraft:iron_leggings,2.7", "minecraft:iron_boots,2.7", "minecraft:golden_helmet,1.5", "minecraft:golden_chestplate,1.5", "minecraft:golden_leggings,1.5", "minecraft:golden_boots,1.5", "minecraft:diamond_helmet,0.5", "minecraft:diamond_chestplate,0.5", "minecraft:diamond_leggings,0.5", "minecraft:diamond_boots,0.5", "minecraft:netherite_helmet,1.9", "minecraft:netherite_chestplate,1.9", "minecraft:netherite_leggings,1.9", "minecraft:netherite_boots,1.9", "minecraft:turtle_helmet,0.75", "ars_nouveau:novice_robes,3.0", "ars_nouveau:novice_leggings,3.0", "ars_nouveau:novice_hood,3.0", "ars_nouveau:novice_boots,3.0", "ars_nouveau:apprentice_robes,3.0", "ars_nouveau:apprentice_leggings,3.0", "ars_nouveau:apprentice_hood,3.0", "ars_nouveau:apprentice_boots,3.0", "ars_nouveau:archmage_robes,3.0", "ars_nouveau:archmage_leggings,3.0", "ars_nouveau:archmage_hood,3.0", "ars_nouveau:archmage_boots,3.0"]
	#
	############################################
	#Disabling this will disable this mods temperature system
	#-------------------------------------------
	#Default: true
	#-------------------------------------------
	"Boolean: Enable Temperature" = true
	#
	############################################
	#This list defines the temperatures of blocks
	#Blocks in this list will apply their temperatures only then they're "lit", or "active"
	#Changes to this list will require you to reset your game for them to be applied
	#-------------------------------------------
	#Default: []
	#-------------------------------------------
	"Lit/Active Block Temperatures" = []
	#
	############################################
	#Disabling this will prevent players from sleeping if they have hyperthermia or hypothermia
	#-------------------------------------------
	#Default: true
	#-------------------------------------------
	"Boolean: Hypothermia/Hyperthermia Allows Sleep" = true

[Hunger]
	#
	############################################
	#The amount of hunger exaustion added to the player regardless of what the player is doing
	#-------------------------------------------
	#Default: 0.1125
	#-------------------------------------------
	#Range: 0.0 ~ 4.0
	"Float: Idle Hunger Exhaustion" = 0.1125
	#
	############################################
	#The amount of time in ticks before hunger exaustion is added to the player regardless of what the player is doing. Set to -1 to disable
	#-------------------------------------------
	#Default: 120
	#-------------------------------------------
	#Range: -1 ~ 1000
	"Integer: Idle Hunger Tick Rate" = 120

[Sleep]
	#
	############################################
	#The maximum amount of sleep time can stack up to. This also determines the maximum amplifier for the tiredness effect
	#-------------------------------------------
	#Default: 20
	#-------------------------------------------
	#Range: 0 ~ 255
	"Integer: Tired Time Stacks" = 20
	#
	############################################
	#Disabling this will disable this mods sleep management system
	#-------------------------------------------
	#Default: true
	#-------------------------------------------
	"Boolean: Enable Sleep" = true
	#
	############################################
	#Disabling this will prevent the player from sleeping during the day even if they have the tiredness effect
	#-------------------------------------------
	#Default: true
	#-------------------------------------------
	"Boolean: Can Sleep During Day" = true
	#
	############################################
	#The amount of ticks after the Initial Tired Time before the amplifier of the tiredness effects increases
	#-------------------------------------------
	#Default: 12000
	#-------------------------------------------
	#Range: 0 ~ 240000
	"Integer: Tired Time Step" = 12000
	#
	############################################
	#The amount of ticks after the player has not slept before The tiredness effect starts to manifest
	#-------------------------------------------
	#Default: 24000
	#-------------------------------------------
	#Range: 0 ~ 240000
	"Integer: Initial Tired Time" = 24000

[Stamina]
	#
	############################################
	#Disabling this will disable this mods stamina system and energy management system
	#-------------------------------------------
	#Default: true
	#-------------------------------------------
	"Boolean: Enable Stamina" = true

[Hygiene]
	#
	############################################
	#Disabling this will disable this mods hygiene system
	#This doesnt really do anything as there isn't really a hygiene system yet
	#-------------------------------------------
	#Default: true
	#-------------------------------------------
	"Boolean: Temperature Update Speed" = true

[Micellaneous]
	#
	############################################
	#Enable Debug mode to have some informational stuff print on your console
	#-------------------------------------------
	#Default: false
	#-------------------------------------------
	"Boolean: Debug Mode" = false

