
[Temperature]
	#The x offset from the center of the screen where the temperature should render
	#Range: -200 ~ 200
	"Temperature X Offset" = -66
	#The y offset from the top of the screen where the temperature should render
	#Range: -200 ~ 200
	"Temperature Y Offset" = 5
	#Allowed Values: HOTBAR, NUMBERS, BAR
	"Temperature Display Mode" = "HOTBAR"
	#If Enabled, temperature will be displayed in fahrenheit if the display mode is set to NUMBERS
	"Display In Fahrenheit" = false

