
[sleep]
	#Disabling this will disable this mods sleep management system
	"Enable Sleep" = false
	#The amount of ticks after the player has not slept before The tiredness effect starts to manifest
	#Range: 0 ~ 240000
	"Initial Tired Time" = 96000
	#The maximum amount of sleep time can stack up to. This also determines the maximum amplifier for the tiredness effect
	#Range: 0 ~ 255
	"Tired Time Stacks" = 20
	#Disabling this will disable the color changing of the screen when you need sleep
	"Enable Tired Overlay" = true
	#The amount of ticks after the Initial Tired Time before the amplifier of the tiredness effects increases
	#Range: 0 ~ 240000
	"Tired Time Step" = 12000
	#Disabling this will prevent the player from sleeping during the day even if they have the tiredness effect
	"Can Sleep During Day" = true

[thirst]
	#Disabling this will disable this mods thirst system
	"Enable Thirst" = true
	#The amount of time in ticks before thirst exaustion is added to the player regardless of what the player is doing. Set to -1 to disable
	#Range: -1 ~ 1000
	"Idle Thirst Tick Rate" = 140
	#The amount of thirst exaustion added to the player regardless of what the player is doing
	#Range: 0.0 ~ 4.0
	"Idle Thirst Exhaustion" = 0.11249999701976776

[stamina]
	#Disabling this will disable this mods energy/stamina management system
	"Enable Stamina" = true

[temperature]
	#Disabling this will prevent players from sleeping if they have hyperthermia or hypothermia
	"Enable Hypothermia/Hyperthermia Allow Sleep" = true
	#This determines the mode used when deciding the temperature
	#NORMAL Mode: calculates the average temperature of each block around the player
	#BLEND Mode: calculates the average temperature similar to that of NORMAL, but blends the temperature of the target positions with the player's. The blend ratio is determined by your distance from the block
	#Allowed Values: BLEND, NORMAL
	"Temperature Mode" = "BLEND"

[Thirst]
	#
	#This list defines which items replenish thirst when consumed
	#Items in this list will not give any extra effects
	#Default: ["minecraft:sweet_berries,-2", "farmersdelight:milk_bottle,4", "minecraft:pumpkin_pie,-4"]
	"Water Containers (Normal)" = ["minecraft:mushroom_stew,1", "crockpot:milk_bottle,4", "create:builders_tea,14"]
	#
	#This list defines which items replenish thirst when consumed
	#Items in this list will give the chilled effect upon drunk
	#Default: ["minecraft:beetroot_soup,3", "minecraft:potato,0", "minecraft:carrot,0", "create:builders_tea,8", "farmersdelight:tomato_sauce,1", "farmersdelight:cabbage,0", "farmersdelight:cabbage_leaf,0", "farmersdelight:tomato,0", "farmersdelight:onion,0", "farmersdelight:pumpkin_slice,0", "farmersdelight:minced_beef,0", "farmersdelight:mixed_salad,0"]
	"Water Containers (Chilled)" = ["minecraft:beetroot_soup,1", "crockpot:iced_tea,8"]
	#
	#This list defines which items replenish thirst when consumed
	#Items in this list will give the heated effect when drunk
	#Default: ["minecraft:rabbit_stew,0", "farmersdelight:hot_cocoa,4", "farmersdelight:beef_stew,1", "farmersdelight:chicken_soup,5", "farmersdelight:vegetable_soup,5", "farmersdelight:pumpkin_soup,5", "farmersdelight:nether_salad,0", "farmersdelight:dumplings,0", "farmersdelight:stuffed_pumpkin,0", "farmersdelight:fish_stew,1", "farmersdelight:baked_cod_stew,1", "farmersdelight:honey_glazed_ham,-2", "farmersdelight:pasta_with_meatballs,0", "farmersdelight:pasta_with_mutton_chop,0", "farmersdelight:vegetable_noodles,0", "farmersdelight:steak_and_potatoes,0", "farmersdelight:shepherds_pie,0", "farmersdelight:ratatouille,0", "farmersdelight:squid_ink_pasta,0", "farmersdelight:grilled_salmon,0"]
	"Water Containers (Heated)" = ["minecraft:rabbit_stew,1", "crockpot:tea,8", "crockpot:hot_cocoa,8"]
	#
	#This list defines which items replenish thirst when consumed
	#Items in this list will randomly give the thirst effect when drunk
	#Default: ["minecraft:honey_bottle,1", "minecraft:pufferfish,-8", "minecraft:rotten_flesh,-4", "minecraft:poisonous_potato,-8", "minecraft:spider_eye,-8", "minecraft:bread,-6", "minecraft:cookie,-1", "farmersdelight:raw_pasta,-4", "farmersdelight:pie_crust,-2", "farmersdelight:slice_of_cake,-2", "farmersdelight:slice_of_apple_pie,-2", "farmersdelight:slice_of_sweet_berry_cheesecake,-2", "farmersdelight:slice_of_chocolate_pie,-2", "farmersdelight:sweet_berry_cookie,-1", "farmersdelight:honey_cookie,-1", "farmersdelight:cooked_rice,-4"]
	"Water Containers (Thirst)" = ["minecraft:honey_bottle,1"]
	#
	#This list defines which items will replenish thirst and energy
	#Items in this list will gived the energized effect when drunk
	#The energized effect will allow the user to operate even if they've not slept for a while and it replenishes energy
	#Default: ["survive:sugar_water_bottle,2"]
	"Water Containers (Energize)" = ["survive:sugar_water_bottle,2", "crockpot:hot_cocoa,8"]

[developerOptions]
	debug_mode = false

[Temperature]
	#Disabling this will disable this mods temperature system
	"Enable Temperature" = true
	#Enabling this allows players to drink water from flowing water sources. This is only allowed for infinite water sources
	"Allow Drinking From Flowing Water" = true
	#Enabling this will remove the water source block when it is drunk
	"Remove Water Source Block" = false
	#
	#This list defines the temperatures of armors when they're put on
	#Changes to this list will require you to reset your game for them to be applied
	#NOTE: Wool Armor is set to 5.0
	#Default: ["survive:stiffened_honey_helmet,-5.0", "survive:stiffened_honey_chestplate,-5.0", "survive:stiffened_honey_leggings,-5.0", "survive:stiffened_honey_boots,-5.0", "survive:wool_hat,5.0", "survive:wool_jacket,5.0", "survive:wool_pants,5.0", "survive:wool_boots,5.0", "minecraft:chainmail_helmet,0.1", "minecraft:chainmail_chestplate,0.1", "minecraft:chainmail_leggings,0.1", "minecraft:chainmail_boots,0.1", "minecraft:leather_helmet,4.0", "minecraft:leather_chestplate,4.0", "minecraft:leather_leggings,4.0", "minecraft:leather_boots,4.0", "minecraft:iron_helmet,2.7", "minecraft:iron_chestplate,2.7", "minecraft:iron_leggings,2.7", "minecraft:iron_boots,2.7", "minecraft:golden_helmet,1.5", "minecraft:golden_chestplate,1.5", "minecraft:golden_leggings,1.5", "minecraft:golden_boots,1.5", "minecraft:diamond_helmet,0.5", "minecraft:diamond_chestplate,0.5", "minecraft:diamond_leggings,0.5", "minecraft:diamond_boots,0.5", "minecraft:netherite_helmet,1.9", "minecraft:netherite_chestplate,1.9", "minecraft:netherite_leggings,1.9", "minecraft:netherite_boots,1.9", "minecraft:turtle_helmet,0.75", "ars_nouveau:novice_robes,3.0", "ars_nouveau:novice_leggings,3.0", "ars_nouveau:novice_hood,3.0", "ars_nouveau:novice_boots,3.0", "ars_nouveau:apprentice_robes,3.0", "ars_nouveau:apprentice_leggings,3.0", "ars_nouveau:apprentice_hood,3.0", "ars_nouveau:apprentice_boots,3.0", "ars_nouveau:archmage_robes,3.0", "ars_nouveau:archmage_leggings,3.0", "ars_nouveau:archmage_hood,3.0", "ars_nouveau:archmage_boots,3.0"]
	"Armor Temperature Modifiers" = ["survive:stiffened_honey_helmet,-5.0", "survive:stiffened_honey_chestplate,-5.0", "survive:stiffened_honey_leggings,-5.0", "survive:stiffened_honey_boots,-5.0", "survive:wool_hat,5.0", "survive:wool_jacket,5.0", "survive:wool_pants,5.0", "survive:wool_boots,5.0", "minecraft:chainmail_helmet,0.1", "minecraft:chainmail_chestplate,0.1", "minecraft:chainmail_leggings,0.1", "minecraft:chainmail_boots,0.1", "minecraft:leather_helmet,4.0", "minecraft:leather_chestplate,4.0", "minecraft:leather_leggings,4.0", "minecraft:leather_boots,4.0", "minecraft:iron_helmet,2.7", "minecraft:iron_chestplate,2.7", "minecraft:iron_leggings,2.7", "minecraft:iron_boots,2.7", "minecraft:golden_helmet,1.5", "minecraft:golden_chestplate,1.5", "minecraft:golden_leggings,1.5", "minecraft:golden_boots,1.5", "minecraft:diamond_helmet,0.5", "minecraft:diamond_chestplate,0.5", "minecraft:diamond_leggings,0.5", "minecraft:diamond_boots,0.5", "minecraft:netherite_helmet,1.9", "minecraft:netherite_chestplate,1.9", "minecraft:netherite_leggings,1.9", "minecraft:netherite_boots,1.9", "minecraft:turtle_helmet,0.75", "iceandfire:sheep_helmet,9", "iceandfire:sheep_chestplate,9", "iceandfire:sheep_leggings,9", "iceandfire:sheep_boots,9", "rankine:brigandine_helmet,4.0", "rankine:brigandine_chestplate,4.0", "rankine:brigandine_leggings,4.0", "rankine:brigandine_boots,4.0"]
	#
	#This list defines the temperatures of blocks
	#Changes to this list will require you to reset your game for them to be applied
	#NOTE: Lava is set to 10.0
	#Default: []
	"Block Temperatures" = []
	#
	#This list defines the temperatures of blocks
	#Blocks in this list will apply their temperatures only then they're "lit"
	#Changes to this list will require you to reset your game for them to be applied
	#Default: []
	"Lit Block Temperatures" = []

[hunger]
	#The amount of hunger exaustion added to the player regardless of what the player is doing
	#Range: 0.0 ~ 4.0
	"Idle Hunger Exhaustion" = 0.11249999701976776
	#The amount of time in ticks before hunger exaustion is added to the player regardless of what the player is doing. Set to -1 to disable
	#Range: -1 ~ 1000
	"Idle Hunger Tick Rate" = 120

[hygiene]
	#Disabling this will disable this mods hygiene management system
	"Enable Hygiene" = true

