
[MMAN]
	#
	############################################
	#Default: FAPPY
	############################################
	#
	"Happy Ant" = "FAPPY"

[General]
	#
	############################################
	#Enable this to see debug messages
	############################################
	#Default: false
	############################################
	#
	Debug = false
	#
	############################################
	#Enable this to see 
	############################################
	#Default: 5
	############################################
	#
	River = 5
	#
	############################################
	#Newton
	############################################
	#Default: 10
	############################################
	#
	#Range: 0 ~ 100
	Sea = 10

