
#Electric Furnace Settings
["Electric Furnace"]
	#Maximum Power for the Electric Furnace to store
	#Range: > 0
	"Maximum Power" = 5000
	#Harvest level of the tool that is required to receive the block as an item when mined
	#Range: > 0
	"Harvest Level" = 1
	#Power consumption per tick for the Electric Furnace
	#Range: > 0
	"Power Consumption" = 64
	#Power I/O per tick for the Electric Furnace
	#Range: > 0
	"Maximum Transfer" = 1000

#Primitive Stirling Generator Settings
["Primitive Stirling Generator"]
	#Power generation per tick
	#Range: > 0
	"Generation (Per Tick)" = 40
	#Power generation to send per tick
	#Range: > 0
	"Output Rate" = 1000
	#Maximum power for the Primitive Stirling Generator to store
	#Range: > 0
	"Maximum Power" = 100000
	#Harvest level of the tool that is required to receive the block as an item when mined
	#Range: > 0
	"Harvest Level" = 1

#Distillation Unit Settings
["Distillation Unit"]
	#Maximum Power for the Distillation Unit to store
	#Range: > 0
	"Maximum Power" = 5000
	#Harvest level of the tool that is required to receive the block as an item when mined
	#Range: > 0
	"Harvest Level" = 1
	#Power consumption per tick for the Distillation Unit
	#Range: > 0
	"Power Consumption" = 64
	#Power I/O per tick for the Distillation Unit
	#Range: > 0
	"Maximum Transfer" = 2500

#World Generation Settings
["World Generation"]
	#Enable/Disable Voluminous Energy biomes
	"Enable VE Biomes" = true
	#Enable/Disable all Voluminous Energy changes to feature generation
	"World Generation" = true

	#Feature Generation
	["World Generation"."Feature Generation"]
		#Oil Lake Chance (Lower = Higher chance)
		#Range: > 10
		"Oil Lake Chance" = 80
		#Enable/Disable Oil Lakes
		"Oil Lakes" = true
		#Oil Geyser Chance (Lower = Higher chance)
		#Range: > 10
		"Oil Geyser Chance" = 2520
		#Enable/Disable Oil Geysers
		"Oil Geysers" = false

	#Ore Generation
	["World Generation"."Ore Generation"]

		#Cinnabar Ore Settings
		["World Generation"."Ore Generation"."Cinnabar Ore Settings"]
			#Range: 0 ~ 256
			"Cinnabar Maximum Height" = 256
			#Range: > 0
			"Cinnabar Size" = 6
			#Enable/Disable generation of Cinnabar Ore
			"Enable Cinnabar Ore" = true
			#Range: > 0
			"Harvest Level" = 2
			#Range: 1 ~ 256
			"Cinnabar Bottom Offset" = 1
			#Range: 0 ~ 256
			"Cinnabar Height Offset" = 0
			#Range: > 1
			"Cinnabar Weight" = 9

		#Saltpeter Ore Settings
		["World Generation"."Ore Generation"."Saltpeter Ore Settings"]
			#Range: > 0
			"Harvest Level" = 1
			#Enable/Disable generation of Saltpeter Ore
			"Enable Saltpeter Ore" = true
			#Range: > 1
			"Saltpeter Weight" = 4
			#Range: > 0
			"Saltpeter Size" = 33
			#Range: 0 ~ 256
			"Saltpeter Maximum Height" = 256
			#Range: 1 ~ 256
			"Saltpeter Bottom Offset" = 55
			#Range: 0 ~ 256
			"Saltpeter Height Offset" = 0

		#Galena Ore Settings
		["World Generation"."Ore Generation"."Galena Ore Settings"]
			#Range: > 1
			"Galena Weight" = 3
			#Range: > 0
			"Harvest Level" = 2
			#Enable/Disable generation of Galena Ore
			"Enable Galena Ore" = true
			#Range: 0 ~ 16
			"Galena Light Glow Level" = 4
			#Range: 0 ~ 256
			"Galena Height Offset" = 0
			#Range: 0 ~ 256
			"Galena Maximum Height" = 32
			#Range: 1 ~ 256
			"Galena Bottom Offset" = 12
			#Range: > 0
			"Galena Size" = 6

		#Rutile Ore Settings
		["World Generation"."Ore Generation"."Rutile Ore Settings"]
			#Enable/Disable generation of Rutile Ore
			"Enable Rutile Ore" = true
			#Range: > 0
			"Harvest Level" = 3
			#Range: > 0
			"Rutile Size" = 4
			#Range: 0 ~ 256
			"Rutile Maximum Height" = 16
			#Range: > 1
			"Rutile Weight" = 3
			#Range: 1 ~ 256
			"Rutile Bottom Offset" = 1
			#Range: 0 ~ 256
			"Rutile Height Offset" = 0

		#Bauxite Ore Settings
		["World Generation"."Ore Generation"."Bauxite Ore Settings"]
			#Range: > 0
			"Bauxite Size" = 8
			#Range: > 0
			"Harvest Level" = 1
			#Range: 0 ~ 256
			"Bauxite Maximum Height" = 60
			#Range: 1 ~ 256
			"Bauxite Bottom Offset" = 10
			#Range: 0 ~ 256
			"Bauxite Height Offset" = 0
			#Enable/Disable generation of Bauxite Ore
			"Enable Bauxite Ore" = true
			#Range: > 1
			"Bauxite Weight" = 16

#Stirling Generator Settings
["Stirling Generator"]
	#Maximum Power for the Stirling Generator to store
	#Range: > 0
	"Maximum Power" = 5120000
	#Harvest level of the tool that is required to receive the block as an item when mined
	#Range: > 0
	"Harvest Level" = 1
	#Fallback value for power generation for the Stirling Generator
	#Range: > 0
	"Fallback Generation Rate" = 128
	#Maximum power to send out per tick for the Stirling Generator
	#Range: > 0
	"Maximum Transfer" = 128000

#Centrifugal Agitator Settings
["Centrifugal Agitator"]
	#Maximum Power for the Centrifugal Agitator to store
	#Range: > 0
	"Maximum Power" = 5000
	#Harvest level of the tool that is required to receive the block as an item when mined
	#Range: > 0
	"Harvest Level" = 1
	#Power consumption per tick for the Centrifugal Agitator
	#Range: > 0
	"Power Consumption" = 40
	#Power I/O per tick for the Centrifugal Agitator
	#Range: > 0
	"Maximum Transfer" = 1000

#Compressor Settings
[Compressor]
	#Maximum Power for the Compressor to store
	#Range: > 0
	"Maximum Power" = 5000
	#Harvest level of the tool that is required to receive the block as an item when mined
	#Range: > 0
	"Harvest Level" = 1
	#Power consumption per tick for the Compressor
	#Range: > 0
	"Power Consumption" = 40
	#Power I/O per tick for the Compressor
	#Range: > 0
	"Maximum Transfer" = 1000

#Gas Furnace Settings
["Gas Furnace"]
	#Harvest level of the tool that is required to receive the block as an item when mined
	#Range: > 0
	"Harvest Level" = 1

#Pump Settings
[Pump]
	#Maximum Power for the Pump to store
	#Range: > 0
	"Maximum Power" = 5000
	#Harvest level of the tool that is required to receive the block as an item when mined
	#Range: > 0
	"Harvest Level" = 1
	#Power consumption per tick for the Pump
	#Range: > 0
	"Power Consumption" = 16
	#Power I/O per tick for the Pump
	#Range: > 0
	"Maximum Transfer" = 1000

#Aqueoulizer Settings
[Aqueoulizer]
	#Maximum Power for the Aqueoulizer to store
	#Range: > 0
	"Maximum Power" = 5000
	#Harvest level of the tool that is required to receive the block as an item when mined
	#Range: > 0
	"Harvest Level" = 1
	#Power consumption per tick for the Aqueoulizer
	#Range: > 0
	"Power Consumption" = 40
	#Power I/O per tick for the Aqueoulizer
	#Range: > 0
	"Maximum Transfer" = 1000

#Air Compressor Settings
["Air Compressor"]
	#Maximum Power for the Air Compressor to store
	#Range: > 0
	"Maximum Power" = 5000
	#Harvest level of the tool that is required to receive the block as an item when mined
	#Range: > 0
	"Harvest Level" = 1
	#Power consumption per tick for the Air Compressor
	#Range: > 0
	"Power Consumption" = 24
	#Power I/O per tick for the Air Compressor
	#Range: > 0
	"Maximum Transfer" = 1000

#Crusher Settings
[Crusher]
	#Maximum power for the Crusher to store
	#Range: > 0
	"Maximum Power" = 5000
	#Harvest level of the tool that is required to receive the block as an item when mined
	#Range: > 0
	"Harvest Level" = 1
	#Power consumption per tick for the Crusher
	#Range: > 0
	"Power Consumption" = 40
	#Power I/O per tick for the Crusher
	#Range: > 0
	"Maximum Transfer" = 1000

#Combustion Generator Settings
["Combustion Generator"]
	#Maximum Power for the Combustion Generator to store
	#Range: > 0
	"Maximum Power" = 5120000
	#Harvest level of the tool that is required to receive the block as an item when mined
	#Range: > 0
	"Harvest Level" = 1
	#The fixed process time for the Combustion Generator is Balanced Mode is not used.
	#Range: > 0
	"Fixed Process Time" = 1600
	#Maximum power to send out per tick for the Combustion Generator
	#Range: > 0
	"Maximum Transfer" = 512000
	#If true, the Combustion Generator will use the process time from the oxidizer's recipe rather than the static process time
	"Balanced Mode" = false

#General Settings
[General]
	#Allow pipes to extract fluids from fluid input tanks. Disabling this means that only fluid outputs can be extracted from Tile Entites
	"Allow Extraction from Input Tanks" = false

#Electrolyzer Settings
[Electrolyzer]
	#Maximum Power for the Electrolyzer to store
	#Range: > 0
	"Maximum Power" = 5000
	#Harvest level of the tool that is required to receive the block as an item when mined
	#Range: > 0
	"Harvest Level" = 1
	#Power consumption per tick for the Electrolyzer
	#Range: > 0
	"Power Consumption" = 40
	#Power I/O per tick for the Electrolyzer
	#Range: > 0
	"Maximum Transfer" = 1000

